# Generated by Django 5.1.4 on 2025-01-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_materia_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='parcial',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primer Parcial'), (2, 'Segundo Parcial')], null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='semestre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primer Semestre'), (2, 'Segundo Semestre')], null=True),
        ),
    ]
