# Generated by Django 5.1.4 on 2025-01-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_nota_parcial_nota_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='parcial',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primer Parcial'), (2, 'Segundo Parcial'), (3, 'Tercer Parcial'), (4, 'Cuarto Parcial')], null=True),
        ),
    ]
